#!/bin/bash
tim2sec() {
mult=1
arg="$1"
inu=0
while [ ${#arg} -gt 0 ]; do
prev="${arg%:*}"
if [ "$prev" = "$arg" ]; then
curr="${arg#0}"
prev=""
else
curr="${arg##*:}"
curr="${curr#0}"
fi
curr="${curr%.*}"
inu=$((inu + curr * mult))
mult=$((mult * 60))
arg="$prev"
done
echo "$inu"
}
function convert() {
local -i bytes=$1
if [[ $bytes -lt 1024 ]]; then
echo "${bytes} B"
elif [[ $bytes -lt 1048576 ]]; then
echo "$(((bytes + 1023) / 1024)) KB"
elif [[ $bytes -lt 1073741824 ]]; then
echo "$(((bytes + 1048575) / 1048576)) MB"
else
echo "$(((bytes + 1073741823) / 1073741824)) GB"
fi
}

clear
xrayy=$(cat /var/log/xray/access.log | wc -l)
if [[ xrayy -le 5 ]]; then
  systemctl restart xray
fi
xraylimit
vm=($(cat /etc/xray/config.json | grep "^#vmg" | awk '{print $2}' | sort -u))
echo -n >/tmp/vm
for db1 in ${vm[@]}; do
  logvm=$(cat /var/log/xray/access.log | grep -w "email: ${db1}" | tail -n 100)
  while read a; do
    if [[ -n ${a} ]]; then
      set -- ${a}
      ina="${7}"
      inu="${2}"
      anu="${3}"
      enu=$(echo "${anu}" | sed 's/tcp://g' | sed '/^$/d' | cut -d. -f1,2,3)
      now=$(tim2sec ${timenow})
      client=$(tim2sec ${inu})
      nowt=$(((${now} - ${client})))
      if [[ ${nowt} -lt 40 ]]; then
        cat /tmp/vm | grep -w "${ina}" | grep -w "${enu}" >/dev/null
        if [[ $? -eq 1 ]]; then
          echo "${ina} ${inu} WIB : ${enu}" >>/tmp/vm
          splvm=$(cat /tmp/vm)
        fi
      fi
    fi
  done <<<"${logvm}"
done
if [[ ${splvm} != "" ]]; then
  for vmuser in ${vm[@]}; do
    vmhas=$(cat /tmp/vm | grep -w "${vmuser}" | wc -l)
    tess=0
    if [[ ${vmhas} -gt $tess ]]; then
      byt=$(cat /etc/limit/vmess/${vmuser})
      gb=$(convert ${byt})
      lim=$(cat /etc/vmess/${vmuser})
      lim2=$(convert ${lim})
      echo -e "$COLOR1${NC} USERNAME : \033[0;33m$vmuser"
      echo -e "$COLOR1${NC} IP LOGIN : \033[0;33m$vmhas"
      echo -e "$COLOR1${NC} USAGE : \033[0;33m$gb"
      echo -e "$COLOR1${NC} LIMIT : \033[0;33m$lim2"
      echo -e ""
    fi
  done
fi
