#!/bin/bash
source <(curl -sSL https://raw.githubusercontent.com/emirjorge/Script-Z/master/CHUMO/msg-bar/msg)
in_opcion_down(){
  dat=$1
  length=${#dat}
  cal=$(( 22 - $length / 2 ))
  line=''
  for (( i = 0; i < $cal; i++ )); do
    line+='╼'
  done
  echo -e " $(msg -verm3 "╭$line╼[")$(msg -azu "$dat")$(msg -verm3 "]")"
  echo -ne " $(msg -verm3 "╰╼")\033[37;1m> " && read opcion
}

fun_trans(){ 
	local texto
	local retorno
	declare -A texto
	SCPidioma="${ADM_tmp}/idioma"
	[[ ! -e ${SCPidioma} ]] && touch ${SCPidioma}
	local LINGUAGE=$(cat ${SCPidioma})
	[[ -z $LINGUAGE ]] && LINGUAGE=es
	[[ $LINGUAGE = "es" ]] && echo "$@" && return
	[[ ! -e /usr/bin/trans ]] && wget -O /usr/bin/trans https://raw.githubusercontent.com/rudi9999/VPS-MX-8.0/master/ArchivosUtilitarios/trans &> /dev/null
	[[ ! -e ${ADM_tmp}/texto-adm ]] && touch ${ADM_tmp}/texto-adm
	source ${ADM_tmp}/texto-adm
	if [[ -z "$(echo ${texto[$@]})" ]]; then
		#ENGINES=(aspell google deepl bing spell hunspell apertium yandex)
		#NUM="$(($RANDOM%${#ENGINES[@]}))"
		retorno="$(source trans -e bing -b es:${LINGUAGE} "$@"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
		echo "texto[$@]='$retorno'"  >> ${ADM_tmp}/texto-adm
		echo "$retorno"
	else
		echo "${texto[$@]}"
	fi
}




new_banner(){
  clear
  local="/etc/bannerssh"
  chk=$(cat /etc/ssh/sshd_config | grep Banner)
  if [ "$(echo "$chk" | grep -v "#Banner" | grep Banner)" != "" ]; then
    local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
  else
    echo "" >> /etc/ssh/sshd_config
    echo "Banner /etc/bannerssh" >> /etc/ssh/sshd_config
    local="/etc/bannerssh"
  fi
  title -ama "Instalador del BANNER-SSH/DROPBEAR"
  in_opcion_down "Escriba el BANNER de preferencia en HTML"
  msg -bar
  if [[ "${opcion}" ]]; then
    rm -rf $local  > /dev/null 2>&1
    echo "$opcion" > $local
    [[ ! -e /etc/darnix/message.txt ]] && echo "@darnix0" > /etc/darnix/message.txt
    credi="$(less /etc/darnix/message.txt)"
    echo '<h4 style=text-align:center><font color="#047980">A</font><font color="#0d6e74">D</font><font color="#006462">M</font><font color="#185260">R</font><font color="#006462">u</font><font color="#0d6e74">f</font><font color="#047980">u</font><br><font color="#047980">'$credi'</font></h4>' >> $local
    service sshd restart 2>/dev/null
    service dropbear restart 2>/dev/null
    print_center -verd "Banner Agregado!!!"
    enter
    return 1
  fi
  print_center -ama "Edicion de Banner Canselada!"
  enter
  return 1
}

banner_edit(){
  clear
  chk=$(cat /etc/ssh/sshd_config | grep Banner)
  local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
  nano $local
  service sshd restart 2>/dev/null
  service dropbear restart 2>/dev/null
  msg -bar
  print_center -ama "Edicion de Banner Terminada!"
  enter
  return 1
}

banner_reset(){
  clear
  chk=$(cat /etc/ssh/sshd_config | grep Banner)
  local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
  rm -rf $local
  touch $local
  service sshd restart 2>/dev/null
  service dropbear restart 2>/dev/null
  msg -bar
  print_center -ama "EL BANNER SSH FUE LIMPIADO"
  enter
  return 1
}


  chk=$(cat /etc/ssh/sshd_config | grep Banner)
  local=$(echo "$chk" |grep -v "#Banner" | grep Banner | awk '{print $2}')
  n=1
  title -ama "MENU DE EDICION DE BANNER SSH"
  echo -e " $(msg -verd "[1]") $(msg -verm2 ">") $(msg -azu "NUEVO BANNER SSH")"
  if [[ -e "${local}" ]]; then
    echo -e " $(msg -verd "[2]") $(msg -verm2 ">") $(msg -azu "EDITAR BANNER CON NANO")"
    echo -e " $(msg -verd "[3]") $(msg -verm2 ">") $(msg -azu "RESET BANNER SSH")"
    n=3
  fi
  back
  opcion=$(selection_fun $n)
  case $opcion in
    1)new_banner;;
    2)banner_edit;;
    3)banner_reset;;
    0)return 1;;
  esac
