#!/bin/bash

module="$(pwd)/module"
[ -e "${module}" ] && rm -f "${module}"
wget -q -O "${module}" "https://raw.githubusercontent.com/darnix1/Premium/main/menu/darnix"
[ ! -e "${module}" ] && exit
chmod +x "${module}" 2>/dev/null
source "${module}"
blanco(){
	[[ !  $2 = 0 ]] && {
		echo -e "\033[1;37m$1\033[0m"
	} || {
		echo -ne " \033[1;37m$1:\033[0m "
	}
}

while :
do
    net=$(jq '.inbounds[].streamSettings.network' $config)
    if [[ $net == '"grpc"' ]]; then
        path=$(jq '.inbounds[].streamSettings.grpcSettings.serviceName' $config)
    else
        path=$(jq '.inbounds[].streamSettings.wsSettings.path' $config)
    fi
    
    clear
    msg -bar3
    blanco "       configuracion Path"
    msg -bar3
    col2 "path:" "$path"
    msg -bar3
    col "0)" "VOLVER"
    msg -bar3
    blanco "NUEVO Path" 0
    read opcion
    
    if [[ -z $opcion ]]; then
        vacio
        sleep 0.3
        break
    fi
    
    if [[ $opcion == 0 ]]; then
        break
    fi
    
    mv $config $temp
    if [[ $net == '"grpc"' ]]; then
        echo "cat $temp | jq '.inbounds[].streamSettings.grpcSettings += {serviceName :\"$opcion\"}' >> $config" | bash
    else
        echo "cat $temp | jq '.inbounds[].streamSettings.wsSettings += {path:\"$opcion\"}' >> $config" | bash
    fi
    
    chmod 777 $config
    rm $temp
    clear
    msg -bar2
    blanco "Nuevo path fijado"
    msg -bar2
    sleep 0.2
    systemctl restart xray
done
